on:
  push:
    branches:
      - master
      - main

env:
  MIRROR: downloads
  LUCENE_VERSION: 9.4.1
  ANT_VERSION: 1.10.12

jobs:

  build_wheel:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest ]
        python-version: [ 3.10.11 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download dependencies
        run: |
          curl -O https://${{env.MIRROR}}.apache.org/lucene/pylucene/pylucene-${{env.LUCENE_VERSION}}-src.tar.gz
          gunzip pylucene-${{env.LUCENE_VERSION}}-src.tar.gz
          tar -xvf pylucene-${{env.LUCENE_VERSION}}-src.tar
          rm pylucene-${{env.LUCENE_VERSION}}-src.tar

          curl -O https://${{env.MIRROR}}.apache.org/ant/binaries/apache-ant-${{env.ANT_VERSION}}-bin.tar.gz
          gunzip apache-ant-${{env.ANT_VERSION}}-bin.tar.gz
          tar -xvf apache-ant-${{env.ANT_VERSION}}-bin.tar
          rm apache-ant-${{env.ANT_VERSION}}-bin.tar
          mv apache-ant-${{env.ANT_VERSION}} ant-${{env.ANT_VERSION}}
          echo "$(pwd)/ant-${{env.ANT_VERSION}}/bin" >> $GITHUB_PATH
          
          python -m pip install --user --upgrade build wheel

      - if: startsWith(matrix.os, 'macos')
        name: Configure JCC (macos)
        run: |
          cat pylucene-${{env.LUCENE_VERSION}}/jcc/setup.py | sed 's/enable_shared = False/enable_shared = True/g' > tmp
          mv tmp pylucene-${{env.LUCENE_VERSION}}/jcc/setup.py
          echo "JCC_JDK=${JAVA_HOME}" >> $GITHUB_ENV
          echo "JCC_ARGSEP=';'" >> $GITHUB_ENV
          echo "JCC_LFLAGS=-L${JAVA_HOME}lib;-ljava;-L${JAVA_HOME}lib/server;-ljvm;-Wl,-rpath=${JAVA_HOME}lib:${JAVA_HOME}lib/server" >> $GITHUB_ENV

      - name: Install JCC
        run: |
          cd pylucene-${{env.LUCENE_VERSION}}
          pushd jcc
          python setup.py build
          echo "---------------- BUILD COMPLETE ----------------"
          python setup.py install --help
          echo "--------------- INSTALL COMPLETE ---------------"
          popd          

      - name: Install PyLucene
        run: |
          cd pylucene-${{env.LUCENE_VERSION}}
          ANT=$(which ant) PYTHON=$(which python) JCC="python -m jcc --shared --wheel" NUM_FILES=10 make

      - name: Upload wheel
        run: |
          mv pylucene/dist/*.whl .
          
          git config --global user.email "harryscells@gmail.com"
          git config --global user.name "Harry Scells"
          git add -f *.whl
          git commit -m ":robot: Update ${{matrix.os}} wheel for pylucene ${{env.LUCENE_VERSION}}"
          git push
              
