on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  MIRROR: downloads
  LUCENE_VERSION: 9.12.0
  ANT_VERSION: 1.10.14

jobs:

  setup:
    strategy:
      matrix:
        os: [ macos-15, ubuntu-latest ]
        python-version: [ 3.12 ]
  
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
  
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
  
      - name: Download pylucene
        run: |
          curl https://downloads.apache.org/lucene/pylucene/pylucene-10.0.0-src.tar.gz | tar -xz --strip-components=1

      - name: Install JCC (ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        env:
          JCC_JDK: ${{ env.JAVA_HOME }}
          JCC_ARGSEP: ";"
          JCC_LFLAGS: "-L${{ env.JAVA_HOME }}/lib;-ljava;-L${{ env.JAVA_HOME }}/lib/server;-ljvm;-Wl,-rpath=${{ env.JAVA_HOME }}/lib:${{ env.JAVA_HOME }}/lib/server"        
        run: |
          pip install build setuptools
          cd jcc \
            && NO_SHARED=1 python -m build -nw \
            && pip install dist/*.whl \
            && cd ../
          make all install JCC='python -m jcc' PYTHON=python NUM_FILES=16 MODERN_PACKAGING=true

      - name: Install JCC (macos)
        if: startsWith(matrix.os, 'macos')
        env:
          JCC_JDK: ${{ env.JAVA_HOME }}
        run: |
          pip install build setuptools
          cd jcc \
            && NO_SHARED=1 python -m build -nw \
            && pip install dist/*.whl \
            && cd ../
          make all install JCC='python -m jcc' PYTHON=python NUM_FILES=16 MODERN_PACKAGING=true

      - name: Upload wheel
        run: |       
          git config --global user.email "harryscells@gmail.com"
          git config --global user.name "Harry Scells"
          git add -f dist/*.whl
          git commit -m ":robot: Update ${{matrix.os}} wheel for pylucene ${{env.LUCENE_VERSION}}"
          git pull --rebase --autostash
          git push
