on:
  push:
    branches:
      - master
      - main

env:
  MIRROR: downloads
  LUCENE_VERSION: 9.4.1
  ANT_VERSION: 1.10.12

jobs:

  build_wheel:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.10.11 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download dependencies
        run: |
          curl -O https://${{env.MIRROR}}.apache.org/lucene/pylucene/pylucene-${{env.LUCENE_VERSION}}-src.tar.gz
          gunzip pylucene-${{env.LUCENE_VERSION}}-src.tar.gz
          tar -xvf pylucene-${{env.LUCENE_VERSION}}-src.tar
          mv pylucene-${{env.LUCENE_VERSION}} pylucene
          rm pylucene-${{env.LUCENE_VERSION}}-src.tar

          curl -O https://${{env.MIRROR}}.apache.org/ant/binaries/apache-ant-${{env.ANT_VERSION}}-bin.tar.gz
          gunzip apache-ant-${{env.ANT_VERSION}}-bin.tar.gz
          tar -xvf apache-ant-${{env.ANT_VERSION}}-bin.tar
          rm apache-ant-${{env.ANT_VERSION}}-bin.tar
          mv apache-ant-${{env.ANT_VERSION}} ant
          echo "$(pwd)/ant/bin" >> $GITHUB_PATH
          
          python -m pip install --user --upgrade build wheel

      - name: Install JCC
        run: |
          cd pylucene
          pushd jcc
          python setup.py build
          python setup.py install
          popd

      - name: Install PyLucene
        run: |
          cd pylucene
          ANT=$(which ant) PYTHON=$(which python) JCC="python -m jcc --shared --wheel" NUM_FILES=10 make

      - name: Upload wheel
        run: |
          mv pylucene/dist/*.whl .
          git add -f *.whl
          git config --local user.email "harryscells@gmail.com"
          git config --local user.name "Harry Scells"
          git commit -m ":robot: Update ${{matrix.os}} wheel for pylucene ${{env.LUCENE_VERSION}}"
          git push
              
