on:
  release:
    types: [ published ]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: build_wheel
    environment:
      name: pypi
      url: https://pypi.org/p/pylucene-packaged
    permissions:
      id-token: write
    steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1